spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecom_order?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 18092786035
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.javaee_ecomorder.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: JavaEE-Ecom-Order-Secret-Key
  expire-hours: 2

logging:
  level:
    com.example.javaee_ecomorder: debug
